projects:
  globals:
    stage: dns
    account_number: "377855031956"

  terraform:
    account-settings:
      vars: {}


    cloudtrail:
      vars: {}      

    dns-delegated:
      vars:
        zone_config:
          - subdomain: gbl
            zone_name: tzlsvc.net

    dns-primary:
      vars:
        domain_names:
        - tzlsvc.net
        - tzlsbx.net

    iam-delegated-roles:
      vars:
        exclude_roles: ["helm"]
