projects:
  globals:
    stage: sbx
    account_number: "168343291205"

  terraform:
    account-settings:
      vars: {}

    cloudtrail:
      vars: {}

    dns-delegated:
      vars:
        zone_config:
          - subdomain: sbx
            zone_name: gbl.tzlsvc.net
              
    iam-delegated-roles:
      vars: {}
