projects:
  globals:
    stage: sbx
    account_number: "168343291205"

  terraform:
    vpc:
      vars:
        cidr_block: "10.101.64.0/18"
        nat_gateway_enabled: false
        nat_instance_enabled: true
        nat_instance_type: "t3.micro"
        availability_zones: ["us-east-2a", "us-east-2b", "us-east-2c"]
